### PR TITLE
third shot for germany

### PR DESCRIPTION
**Pull request by r00tk1d**
added KEY for Pfizer and Moderna
updated vaccine motives for third shot

### CODE REVIEW

**Comment by rbignon** [comment]
Hello,

Thank you for your pull request. As there is another one (#287) on the same topic, should I merge this one or the other one?

**Comment by r00tk1d** [comment]
I think there are the same but this one adds one more motive_key I found ("booster") so maybe merge this one

**Comment by clemux** [comment]
I made the tests pass, but I don't know if they do what we want them to do.

https://github.com/clemux/doctoshotgun/commit/206153f62dcc6f9c6357ef64ed1eb1594ee5a690

Made a PR to @r00tk1d 's branch on their repository, in case that's easier for reviewing/merging.  https://github.com/r00tk1d/doctoshotgun/pull/1

Please see my comments there.

**Comment by r00tk1d** [comment]
Great! tbh i dont know either. Looks good to me though. I'll merge it and @rbignon can also review it here

**Pull request merged**
