### PR TITLE
Add AstraZeneca choice

### PR DESCRIPTION
**Pull request by namnhatpham1995**
input --astrazeneca or -a to choose AstraZeneca vaccine

### CODE REVIEW

**Comment by rbignon** [comment]
I think most people do not want to be vaccinated with the AstraZeneca vaccine. It is better if it is not selected by default.

**Comment by namnhatpham1995** [comment]
For students studying abroad like me, waiting for the vaccinating slot with Pfizer or Moderna requires lots of time because of the high demand so AstraZeneca is an acceptable option.
On the other hands, Janssen vaccine uses the same technology as AstraZeneca so I think these two are equal in positive and negative effects. 
Therefore, I think if there are demands on choosing vaccine, user can input manually and the default mode is open for any kind of vaccine.

**Comment by rbignon** [comment]
You are right about Janssen and the fact that users who are demanding can give parameters. However, there is another reason to not enable AstraZeneca by default, in France AstraZeneca can't be used for people younger than 55 years old.

**Comment by rbignon** [comment]
This PR has been merged, thank you.

**Pull request closed without merging**
