### PR TITLE
exclude specific weekdays

### PR DESCRIPTION
**Pull request by ThomasParistech**
Add possibility to exclude specific weekdays, in addition to restricting the start and end dates.

### CODE REVIEW

**Comment by ThomasParistech** [comment]
Useful when you practice a sport every Thursday and you don't want to be KO because you were vaccinated the day before ;)

**Comment by ThomasParistech** [comment]
Hello @rbignon,

Thank you very much for your script!

However I don't quite understand what's wrong with this tiny PR. Several PRs and commits have been merged//pushed  since I opened it and it seems like this one fell into oblivion

**Comment by rbignon** [comment]
Hello,

Thank you for your contribution.

Nothing wrong, I just didn't take the time to review it.

I think it would be better to rename the option `--exclude-weekday`, and `-w` instead of `-e` (but for this one I'm not sure).

You should also catch `KeyError` when the argument isn't a valide weekday:

```
$ ./doctoshotgun.py fr paris blah@blah.org --weekdays-exclude blah
Traceback (most recent call last):
  File "/home/rom1/src/doctoshotgun/./doctoshotgun.py", line 948, in <module>
    sys.exit(Application().main())
  File "/home/rom1/src/doctoshotgun/./doctoshotgun.py", line 848, in main
    excluded_weekdays = set(sorted([_day_names[d.title()] for d in args.weekdays_exclude]))
  File "/home/rom1/src/doctoshotgun/./doctoshotgun.py", line 848, in <listcomp>
    excluded_weekdays = set(sorted([_day_names[d.title()] for d in args.weekdays_exclude]))
KeyError: 'Blah'
```
Also, if you supply several excluded weekdays, only the first one seems to be taken account:

```
$ ./doctoshotgun.py fr paris blah@blah.org -e monday -e friday
Starting to look for vaccine slots for Romain Bignon between 2021-12-08 and 2021-12-15...
Excluded weekdays: Friday
Vaccines: 3e.*Pfizer, 3e.*Moderna
Country: fr 
This may take a few minutes/hours, be patient!
```

**Comment by ThomasParistech** [comment]
thanks for responding so quickly

I used "--weekday-exclude" to mimic the "--center-exclude" command. You're right about the "-w", makes more sense
Good point, I'll catch the key error instead

As mentioned in the argument description, the option accepts several arguments, e.g. "-e monday friday". Passing several times the option "-e" just overwrites it

**Comment by rbignon** [comment]
> I used "--weekday-exclude" to mimic the "--center-exclude" command. You're right about the "-w", makes more sense 

Hm, you are right. Perhaps juste --weekday-exclude in singular (see bellow)

> As mentioned in the argument description, the option accepts several arguments, e.g. "-e monday friday". Passing several times the option "-e" just overwrites it

The correct behavior would be to provide several `-e` arguments instead of only one separated by white spaces.

**Pull request merged**
