### PR TITLE
try/except blocks for connection error to prevent script from stopping

### PR DESCRIPTION
**Pull request by rjkerrison**
To prevent the script from stopping during times of poor connectivity, we catch any ConnectionError or similar and retry the current step after 60 seconds.

### CODE REVIEW

**Comment by rbignon** [comment]
Hello,

Thank you for your patch. However, I would like to find a way to use the retry mechanism of requests to prevent try/except on each request.

Also, why waiting 60 seconds and not only something like 5 seconds?

**Comment by nicolaus-hee** [comment]
On a similar note, I noticed that some url queries take (~3x) longer than woob's standard timeout and added `self.TIMEOUT = 60` to `class Doctolib(LoginBrowser)` > `def __init__()`.

**Comment by rbignon** [comment]
The problem is that I had to replace the default woob Session (which handles timeouts and retries) by the cloudscrape one (to bypass cloudflare protections), but this one does not support giving max_retries on HTTPAdapter.

**Comment by rjkerrison** [comment]
For my use case, I had intermittent wifi and waiting 5 seconds would result in a lot of unnecessary attempts, whereas waiting 60 seconds was just two or three attempts. Without this retrying, the script would fail for me after around an hour, but with it I was able to find my appointment over a few hours. (On that note, thank you so much!)

**Comment by clemux** [comment]
What do you think of rollbacking the timeout changes here, and opening an issue/PR for the addition of a `--timeout` option?

**Comment by rjkerrison** [comment]
Closing this as no longer presents a problem in the latest version

**Pull request closed without merging**
