### PR TITLE
Implement 2-factor authentication during login (by email)

### LINKED ISSUE #37: Error 401
Bonjour,
Merci beaucoup pour votre travail sur ce projet.

Je reçois une erreur 401 lors du lancement du script.

Voici le contenu de mon terminal (avec l'option -d pour debug) :
./doctoshotgun.py -d Paris example.email@gmail.com
Password: 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.doctolib.fr:443
DEBUG:urllib3.connectionpool:https://www.doctolib.fr:443 "GET /sessions/new HTTP/1.1" 200 None
INFO:browser:Response saved to 677dad1389174096842e851184a51d4a
DEBUG:browser:Unable to handle https://www.doctolib.fr/sessions/new
DEBUG:urllib3.connectionpool:https://www.doctolib.fr:443 "POST /login.json HTTP/1.1" 200 None
INFO:browser:Response saved to 0e2f596a8ebd4e27949d4743235cc5c5
DEBUG:browser:Handle https://www.doctolib.fr/login.json with LoginPage
DEBUG:urllib3.connectionpool:https://www.doctolib.fr:443 "GET /account/master_patients.json HTTP/1.1" 401 None
INFO:browser:Response saved to 869a22057d7146148592bdd36c2b2e09
Traceback (most recent call last):
  File "/Users/Victor/Documents/Programmation/Python/doctoshotgun/./doctoshotgun.py", line 420, in <module>
    sys.exit(Application().main())
  File "/Users/Victor/Documents/Programmation/Python/doctoshotgun/./doctoshotgun.py", line 378, in main
    patients = docto.get_patients()
  File "/Users/Victor/Documents/Programmation/Python/doctoshotgun/./doctoshotgun.py", line 207, in get_patients
    self.master_patient.go()
  File "/usr/local/lib/python3.9/site-packages/woob/browser/url.py", line 98, in go
    r = self.browser.location(self.build(**kwargs), params=params, data=data, json=json, method=method, headers=headers or {})
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 911, in location
    response = self.open(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 898, in open
    return super(PagesBrowser, self).open(callback=internal_callback, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 790, in open
    return super(DomainBrowser, self).open(req, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 531, in open
    response = self.session.send(preq,
  File "/Users/Victor/Documents/Programmation/Python/doctoshotgun/./doctoshotgun.py", line 42, in send
    return callback(self, resp)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 527, in inner_callback
    self.raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/woob/browser/browsers.py", line 560, in raise_for_status
    raise ClientError(http_error_msg, response=response)
woob.browser.exceptions.ClientError: 401 Client Error: Unauthorized

Je suis sur Mac OS X. Avez-vous une idée de ce qui pourrait causer le problème ?

### PR DESCRIPTION
**Pull request by aduffeck**
This commit handles the case where 2fa is required by the server.

An email code is requested from the server which can then be entered on the command line to complete the 2fa flow.

Fixes #37, #46 and #55.

### CODE REVIEW

**Comment by rbignon** [comment]
Hello,

Thank you for your contribution. I have no way to test it, but it seems good (and at worst it wouldn't break anything if it does not work).

**Comment by securitygeneration** [comment]
@aduffeck I'm getting an error trying to log in to an account with 2FA:

```
Requesting 2fa code...
Enter auth code: Traceback (most recent call last):
  File "/usr/src/app/./doctoshotgun.py", line 627, in <module>
    sys.exit(Application().main())
  File "/usr/src/app/./doctoshotgun.py", line 529, in main
    if not docto.do_login():
  File "/usr/src/app/./doctoshotgun.py", line 215, in do_login
    code = input("Enter auth code: ")
EOFError: EOF when reading a line
```

**Comment by aduffeck** [comment]
@securitygeneration how do you run doctoshotgun? It looks like it's something non-interactive that doesn't support input?

**Comment by securitygeneration** [comment]
I'm running it via Docker (basically following the readme instructions)

**Comment by aduffeck** [comment]
@securitygeneration I see. can you please try `docker run -it` instead of just `docker run`? That should fix the problem for you.

I'll prepare a pull request to adapt the readme accordingly

**Comment by aduffeck** [comment]
I just created the readme PR at https://github.com/rbignon/doctoshotgun/pull/77

**Comment by securitygeneration** [comment]
Yep, the `-it` runs it interactive, thanks :)

**Pull request merged**
