### PR TITLE
add an option to exclude a list of centers from the search results

### PR DESCRIPTION
**Pull request by strombringer**
Sometimes a doctor only offers the vaccine to known patients but hasn't set up Doctolib accordingly.
With this new parameter you can exclude doctors/centers that you know won't accept your booking.

### CODE REVIEW

**Comment by gitolicious** [comment]
Not related to the PR content directly, but how did you find out about the doctor not accepting new patients for the vaccination?
Would it be reasonable to include a "blacklist" in the script?

**Comment by gitolicious** [comment]
Answering my own question, there are e.g. pediatricians (Kinderärzte) which I guess will only vaccinate children.
Example: https://www.doctolib.de/einzelpraxis/duesseldorf/dr-h-j-kahl-facharztpraxis-fuer-kinder-und-jugendliche

https://www.kinderarzt-dr-kahl.de/
> _ab 07.06.2021 können wir Kindern und Jugendlichen ab 12 Jahren eine Corona-Impfung mit BioNTech anbieten_

**Comment by strombringer** [comment]
> Not related to the PR content directly, but how did you find out about the doctor not accepting new patients for the vaccination?
> Would it be reasonable to include a "blacklist" in the script?

I read it on the doctor's website, not on Doctolib. On Doctolib it was possible to book an appointment but it would've been cancelled by staff.

**Comment by rbignon** [comment]
This PR has been merged, thank you.

**Pull request closed without merging**
